version: '2'

services:
    php:
        container_name: php
        restart: always
        privileged: true
        image: coeus0301/php:v1
        environment:
        - TERM=linux
        - MEMCACHE=Yes
        - REDIS=Yes
        - TIMEZONE=Asia/Shanghai
        volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data/wwwroot:/data/wwwroot:rw
    nginx:
        container_name: nginx
        restart: always
        privileged: true
        image: coeus0301/nginx:1.18
        ports:
        - "80:80"
        - "443:443"
        links:
        - php:php
        volumes_from:
        - php
        environment:
        - PHP_FPM=Yes
        - PHP_FPM_SERVER=php
        - PHP_FPM_PORT=9000
        volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data/www:/data/wwwroot:rw
        - /data/wwwlogs/:/data/wwwlogs:rw
        - /usr/local/nginx/conf:/usr/local/nginx/conf:rw
